friends=["Sakthi","Anathan","Senthil","Pradheesh","Hari"]
lucky_numbers=[2,4,5,7,9,11]
print(friends,lucky_numbers)
friends.append("Jerin")
print(friends)
friends.insert(1,"Vivek")
print(friends)
friends.pop()
print(friends)
